

"use client"

import { useState, useMemo, useEffect } from "react"
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
  CardDescription
} from "@/components/ui/card"
import {
  Table,
  TableHeader,
  TableRow,
  TableHead,
  TableBody,
  TableCell,
} from "@/components/ui/table"
import { Button } from "@/components/ui/button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
    DialogDescription,
    DialogFooter
} from "@/components/ui/dialog"
import { PlusCircle, MoreHorizontal, Edit, Trash2, Clipboard, UserPlus, Redo, Link as LinkIcon, Check } from "lucide-react"
import type { Employee } from "@/lib/types"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { useToast } from "@/hooks/use-toast"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { getAllFromCollection_client, saveDocument, deleteDocument } from "@/lib/firestore-services"
import { Badge } from "@/components/ui/badge"

export default function EmployeesPage() {
  const [employees, setEmployees] = useState<Employee[]>([])
  const [exEmployees, setExEmployees] = useState<Employee[]>([])
  const [isFormOpen, setIsFormOpen] = useState(false)
  const [selectedEmployee, setSelectedEmployee] = useState<Employee | null>(null)
  const [formData, setFormData] = useState<Omit<Employee, 'id' | 'email' | 'password'>>({ name: '', dni: '', phone: '', fixedSalary: 0 });
  const [copiedLink, setCopiedLink] = useState<string | null>(null);
  const { toast } = useToast();

  const fetchData = async () => {
    const [employeesData, exEmployeesData] = await Promise.all([
        getAllFromCollection_client<Employee>('employees'),
        getAllFromCollection_client<Employee>('ex_employees')
    ]);
    setEmployees(employeesData);
    setExEmployees(exEmployeesData);
  }

  useEffect(() => {
    fetchData();
  }, [])
  
  useEffect(() => {
    if (selectedEmployee) {
        setFormData({
            name: selectedEmployee.name,
            dni: selectedEmployee.dni,
            phone: selectedEmployee.phone,
            fixedSalary: selectedEmployee.fixedSalary || 0
        });
    } else {
        setFormData({ name: '', dni: '', phone: '', fixedSalary: 0 });
    }
  }, [selectedEmployee, isFormOpen]);

  const handleCreate = () => {
    setSelectedEmployee(null)
    setIsFormOpen(true)
  }

  const handleEdit = (employee: Employee) => {
    setSelectedEmployee(employee)
    setIsFormOpen(true)
  }

  const handleFormChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const { id, value } = e.target;
    setFormData(prev => ({
        ...prev,
        [id]: id === 'fixedSalary' ? (value === '' ? 0 : Number(value)) : value
    }));
  }

  const handleSave = async () => {
    if (!formData.name || !formData.dni || !formData.phone) {
        toast({ title: "Datos incompletos", description: "Nombre, DNI y teléfono son obligatorios.", variant: "destructive" });
        return;
    }

    const employeeData: Partial<Employee> = {
        name: formData.name,
        dni: formData.dni,
        phone: formData.phone,
        fixedSalary: Number(formData.fixedSalary) || 0,
    };
    
    // Use the existing ID if editing, otherwise a new one will be generated by the service
    await saveDocument('employees', employeeData, selectedEmployee?.id);
    
    toast({ title: "¡Éxito!", description: "El empleado/a ha sido guardado/a." });

    await fetchData();
    setIsFormOpen(false);
    setSelectedEmployee(null);
  }

  const handleDelete = async (employeeToDelete: Employee) => {
    // This now means moving them to a different collection. Deleting from Auth should be a separate, more deliberate action.
    await saveDocument('ex_employees', employeeToDelete, employeeToDelete.id);
    await deleteDocument('employees', employeeToDelete.id);
    await fetchData();
    toast({ title: "Empleado/a archivado/a", description: "El empleado/a ha sido movido/a a ex-empleados." });
  }

  const handleCopyLink = (employeeId: string) => {
    const link = `${window.location.origin}/employee/register?employeeId=${employeeId}`;
    navigator.clipboard.writeText(link);
    setCopiedLink(employeeId);
    setTimeout(() => setCopiedLink(null), 2000);
    toast({ title: "Enlace Copiado", description: "El enlace de registro ha sido copiado al portapapeles."});
  }

  return (
    <div className="space-y-6">
       <Dialog open={isFormOpen} onOpenChange={setIsFormOpen}>
        <DialogContent>
            <DialogHeader>
                <DialogTitle>{selectedEmployee ? "Editar Empleado" : "Nuevo Empleado"}</DialogTitle>
                <DialogDescription>
                {selectedEmployee ? "Modifica los datos del empleado." : "Añade un nuevo empleado. Se generará un link para que complete su registro."}
                </DialogDescription>
            </DialogHeader>
            <div className="space-y-4 py-4">
                <div className="space-y-2">
                    <Label htmlFor="name">Nombre Completo</Label>
                    <Input id="name" value={formData.name} onChange={handleFormChange}/>
                </div>
                 <div className="space-y-2">
                    <Label htmlFor="dni">DNI</Label>
                    <Input id="dni" value={formData.dni} onChange={handleFormChange}/>
                </div>
                 <div className="space-y-2">
                    <Label htmlFor="phone">Teléfono</Label>
                    <Input id="phone" value={formData.phone} onChange={handleFormChange}/>
                </div>
                 <div className="space-y-2">
                    <Label htmlFor="fixedSalary">Sueldo Fijo ($)</Label>
                    <Input id="fixedSalary" type="number" value={formData.fixedSalary || ''} onChange={handleFormChange} placeholder="Ej: 150000"/>
                </div>
            </div>
            <DialogFooter>
                <Button variant="outline" onClick={() => setIsFormOpen(false)}>Cancelar</Button>
                <Button onClick={handleSave}>Guardar</Button>
            </DialogFooter>
        </DialogContent>
       </Dialog>

      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold">Gestión de Empleados</h2>
          <p className="text-muted-foreground">
            Añade, edita o archiva a los empleados de la empresa.
          </p>
        </div>
        <div className="flex items-center gap-2">
           {exEmployees.length > 0 && (
             <p className="text-sm text-muted-foreground">{exEmployees.length} empleado(s) archivado(s).</p>
           )}
            <Button onClick={handleCreate}>
              <PlusCircle className="mr-2 h-4 w-4" />
              Nuevo Empleado
            </Button>
        </div>
      </div>
      <Card>
        <CardContent className="pt-6">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Nombre</TableHead>
                <TableHead>DNI</TableHead>
                <TableHead>Teléfono</TableHead>
                <TableHead>Email / Estado</TableHead>
                <TableHead>Sueldo</TableHead>
                <TableHead className="text-right">Acciones</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {employees.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={6} className="h-24 text-center">
                    No hay empleados registrados.
                  </TableCell>
                </TableRow>
              ) : employees.map((employee) => (
                  <TableRow key={employee.id}>
                    <TableCell className="font-medium">{employee.name}</TableCell>
                    <TableCell>{employee.dni}</TableCell>
                    <TableCell>{employee.phone}</TableCell>
                    <TableCell>
                      {employee.email ? employee.email : (
                          <Badge variant="outline" className="text-orange-500 border-orange-500">
                              Registro Pendiente
                          </Badge>
                      )}
                    </TableCell>
                    <TableCell>${(employee.fixedSalary || 0).toLocaleString('es-AR')}</TableCell>
                    <TableCell className="text-right">
                      {!employee.email && (
                          <Button 
                            variant="outline" 
                            size="sm" 
                            className="mr-2"
                            onClick={() => handleCopyLink(employee.id)}
                          >
                             {copiedLink === employee.id ? <Check className="mr-2 h-4 w-4"/> : <LinkIcon className="mr-2 h-4 w-4"/>}
                             {copiedLink === employee.id ? "Copiado" : "Copiar Link"}
                          </Button>
                      )}
                      <DropdownMenu>
                        <DropdownMenuTrigger asChild>
                          <Button variant="ghost" className="h-8 w-8 p-0">
                            <span className="sr-only">Abrir menú</span>
                            <MoreHorizontal className="h-4 w-4" />
                          </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align="end">
                          <DropdownMenuItem onClick={() => handleEdit(employee)}>
                            <Edit className="mr-2 h-4 w-4" />
                            Editar
                          </DropdownMenuItem>
                          <DropdownMenuItem onClick={() => handleDelete(employee)} className="text-destructive">
                            <Trash2 className="mr-2 h-4 w-4" />
                            Archivar
                          </DropdownMenuItem>
                        </DropdownMenuContent>
                      </DropdownMenu>
                    </TableCell>
                  </TableRow>
                ))}
            </TableBody>
          </Table>
        </CardContent>
      </Card>
    </div>
  )
}
